// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSGPM.Migrations
{
    [DbContext(typeof(DTUcontext))]
    [Migration("20230227133604_CreatingAppropriateClassesForStoringReportStructure")]
    partial class CreatingAppropriateClassesForStoringReportStructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSGPM.DataAccess.Constraint", b =>
                {
                    b.Property<Guid>("ConstraintGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ConstraintCountGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSetGuid")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConstraintGuid");

                    b.ToTable("Constraints");
                });

            modelBuilder.Entity("FSGPM.DataAccess.ConstraintCount", b =>
                {
                    b.Property<Guid>("ConstraintCountGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ConstraintMax")
                        .HasColumnType("int");

                    b.Property<int>("ConstraintMin")
                        .HasColumnType("int");

                    b.HasKey("ConstraintCountGuid");

                    b.ToTable("ConstraintCounts");
                });

            modelBuilder.Entity("FSGPM.DataAccess.DataSet", b =>
                {
                    b.Property<Guid>("DataSetGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DataSetGuid");

                    b.ToTable("DataSets");
                });

            modelBuilder.Entity("FSGPM.DataAccess.Pattern", b =>
                {
                    b.Property<Guid>("PatternGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DataSetGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("DefaultPatternLength")
                        .HasColumnType("bit");

                    b.Property<int>("PatternLenght")
                        .HasColumnType("int");

                    b.Property<string>("PatternText")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PatternGuid");

                    b.ToTable("Patterns");
                });

            modelBuilder.Entity("FSGPM.DataAccess.ReportStatus", b =>
                {
                    b.Property<Guid>("StatusGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProgressStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ReportCompleted")
                        .HasColumnType("bit");

                    b.HasKey("StatusGuid");

                    b.ToTable("ReportStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
