// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FSGPM.Migrations
{
    [DbContext(typeof(DTUcontext))]
    [Migration("20230224161212_FirstMigrationReportStatusModel")]
    partial class FirstMigrationReportStatusModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FSGPM.Models.ReportStatus", b =>
                {
                    b.Property<Guid>("StatusGuid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProgressStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("ReportCompleted")
                        .HasColumnType("bit");

                    b.HasKey("StatusGuid");

                    b.ToTable("ReportStatuses");
                });
#pragma warning restore 612, 618
        }
    }
}
